config/routes.rb
Rails.application.routes.draw do
  resources :triangles
  resources :anagrams
  resources :palindromes
  resources :ordenators
  resources :calcs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"
end

app/models/ordenator.rb
class Ordenator < ApplicationRecord
  
  def inserir_colecao(a)
    x = Ordenator.create(value: a)
    ordenators = Ordenator.all
    max_value = ordenators.max_by { |max| max[:value] }[:value]
    if x.value <= max_value
      puts "Valor criado não é o maior valor e foi substituído com sucesso"
    else
      puts "Valor criado é o maior valor"
    end
  end
  
  def informar_valor(a)
    x = Ordenator.create(value: a)
    ordenator = Ordenator.all
    max_value = ordenator.max_by { |max| max[:value] }[:value]
    puts max_value
  end
  
  def maior_valor(a)
    ordenators = Ordenator.all
    max_value = ordenators.max_by { |max| max[:value] }[:value]
    ordenator = Ordenator.create(value: a)
    if ordenator.value >= max_value
      puts "Maior valor: #{ordenator.value}"
    else
      puts "Maior valor: #{max_value}"
    end
  end
  
  def menor_valor(a)
    ordenators = Ordenator.all
    min_value = ordenators.min_by { |min| min[:value] }[:value]
    ordenator = Ordenator.create(value: a)
    if ordenator.value <= min_value
      puts "Menor valor: #{ordenator.value}"
    else
      puts "Menor valor: #{min_value}"
    end
  end

  def valor_medio
    ordenators = Ordenator.all
    soma = Ordenator.sum(:value)
    qtd = ordenators.count
    med_value = soma/qtd
    puts med_value.to_f
  end

  def valor_mediana
    ordenators = Ordenator.all
    soma = ordenators.sum(:value)
    qtd = ordenators.count
    if qtd % 2 != 0
      med_value = ((soma/qtd) + 1)/2
      puts med_value.to_f
    else
      med_value = soma/qtd
      puts med_value.to_f
    end
  end

end

app/controllers/ordenators_controller.rb
class OrdenatorsController < ApplicationController
  before_action :set_ordenator, only: [:show, :edit, :update, :destroy]

  # GET /ordenators
  # GET /ordenators.json
  def index
    @ordenators = Ordenator.all
  end

  # GET /ordenators/1
  # GET /ordenators/1.json
  def show
  end

  # GET /ordenators/new
  def new
    @ordenator = Ordenator.new
  end

  # GET /ordenators/1/edit
  def edit
  end

  # POST /ordenators
  # POST /ordenators.json
  def create
    @ordenator = Ordenator.new(ordenator_params)

    respond_to do |format|
      if @ordenator.save
        format.html { redirect_to @ordenator, notice: 'Ordenator was successfully created.' }
        format.json { render :show, status: :created, location: @ordenator }
      else
        format.html { render :new }
        format.json { render json: @ordenator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordenators/1
  # PATCH/PUT /ordenators/1.json
  def update
    respond_to do |format|
      if @ordenator.update(ordenator_params)
        format.html { redirect_to @ordenator, notice: 'Ordenator was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordenator }
      else
        format.html { render :edit }
        format.json { render json: @ordenator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordenators/1
  # DELETE /ordenators/1.json
  def destroy
    @ordenator.destroy
    respond_to do |format|
      format.html { redirect_to ordenators_url, notice: 'Ordenator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordenator
      @ordenator = Ordenator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordenator_params
      params.require(:ordenator).permit(:value)
    end
end

app/helpers/ordenators_helper.rb
module OrdenatorsHelper
end

app/views/ordenators/_form.html.erb
<%= form_with(model: ordenator, local: true) do |form| %>
  <% if ordenator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordenator.errors.count, "error") %> prohibited this ordenator from being saved:</h2>

      <ul>
      <% ordenator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ordenators/edit.html.erb
<h1>Editing Ordenator</h1>

<%= render 'form', ordenator: @ordenator %>

<%= link_to 'Show', @ordenator %> |
<%= link_to 'Back', ordenators_path %>

app/views/ordenators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordenators</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordenators.each do |ordenator| %>
      <tr>
        <td><%= ordenator.value %></td>
        <td><%= link_to 'Show', ordenator %></td>
        <td><%= link_to 'Edit', edit_ordenator_path(ordenator) %></td>
        <td><%= link_to 'Destroy', ordenator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <br>
    <% numbers = Ordenator.all %>
    <% if numbers.present? %>
      <tr>
      <% max_value = numbers.max_by { |max| max[:value] }[:value] %>
      <td>Maior Valor: <%= max_value %></td>
    </tr>
    <% else %>
      <tr>
        <td>Não há números cadastrados!</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordenator', new_ordenator_path %>
<%= link_to 'Back', root_path %>

app/views/ordenators/new.html.erb
<h1>New Ordenator</h1>

<%= render 'form', ordenator: @ordenator %>

<%= link_to 'Back', ordenators_path %>

app/views/ordenators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @ordenator.value %>
</p>

<%= link_to 'Edit', edit_ordenator_path(@ordenator) %> |
<%= link_to 'Back', ordenators_path %>