config/routes.rb
Rails.application.routes.draw do
  resources :triangles
  resources :anagrams
  resources :palindromes
  resources :ordenators
  resources :calcs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"
end

app/models/calc.rb
class Calc < ApplicationRecord
  validates :divider, :dividend, presence: true

  def soma(a, b)
    a + b
  end

  def divisao(a, b)
    a / b
  end
  
  def raiz(a)
    Math.sqrt(a)
  end
end

app/controllers/calcs_controller.rb
class CalcsController < ApplicationController
  before_action :set_calc, only: [:show, :edit, :update, :destroy]

  # GET /calcs
  # GET /calcs.json
  def index
    @calcs = Calc.all
  end

  # GET /calcs/1
  # GET /calcs/1.json
  def show
  end

  # GET /calcs/new
  def new
    @calc = Calc.new
  end

  # GET /calcs/1/edit
  def edit
  end

  # POST /calcs
  # POST /calcs.json
  def create
    @calc = Calc.new(calc_params)
    @calc.quotient = @calc.dividend / @calc.divider
    @calc.save
    respond_to do |format|
      if @calc.save
        format.html { redirect_to @calc, notice: 'Calc was successfully created.' }
        format.json { render :show, status: :created, location: @calc }
      else
        format.html { render :new }
        format.json { render json: @calc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calcs/1
  # PATCH/PUT /calcs/1.json
  def update
    @calc.quotient = @calc.dividend / @calc.divider
    @calc.save
    respond_to do |format|
      if @calc.update(calc_params)
        format.html { redirect_to @calc, notice: 'Calc was successfully updated.' }
        format.json { render :show, status: :ok, location: @calc }
      else
        format.html { render :edit }
        format.json { render json: @calc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calcs/1
  # DELETE /calcs/1.json
  def destroy
    @calc.destroy
    respond_to do |format|
      format.html { redirect_to calcs_url, notice: 'Calc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calc
      @calc = Calc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calc_params
      params.require(:calc).permit(:divider, :dividend, :quotient)
    end
end

app/helpers/calcs_helper.rb
module CalcsHelper
end

app/views/calcs/_form.html.erb
<%= form_with(model: calc, local: true) do |form| %>
  <% if calc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calc.errors.count, "error") %> prohibited this calc from being saved:</h2>

      <ul>
      <% calc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :dividend %>
    <%= form.number_field :dividend %>
  </div>
  <div class="field">
    <%= form.label :divider %>
    <%= form.number_field :divider %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calcs/edit.html.erb
<h1>Editing Calc</h1>

<%= render 'form', calc: @calc %>

<%= link_to 'Show', @calc %> |
<%= link_to 'Back', calcs_path %>

app/views/calcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calcs</h1>

<table>
  <thead>
    <tr>
      <th>Dividend</th>
      <th>Divider</th>
      <th>Quotient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calcs.each do |calc| %>
      <tr>
        <td><%= calc.dividend %></td>
        <td><%= calc.divider %></td>
        <td><%= calc.quotient %></td>
        <td><%= link_to 'Show', calc %></td>
        <td><%= link_to 'Edit', edit_calc_path(calc) %></td>
        <td><%= link_to 'Destroy', calc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calc', new_calc_path %>
<%= link_to 'Back', root_path %>

app/views/calcs/new.html.erb
<h1>New Calc</h1>

<%= render 'form', calc: @calc %>

<%= link_to 'Back', calcs_path %>

app/views/calcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Divider:</strong>
  <%= @calc.divider %>
</p>

<p>
  <strong>Dividend:</strong>
  <%= @calc.dividend %>
</p>

<p>
  <strong>Quotient:</strong>
  <%= @calc.quotient %>
</p>

<%= link_to 'Edit', edit_calc_path(@calc) %> |
<%= link_to 'Back', calcs_path %>