config/routes.rb
Rails.application.routes.draw do
  resources :triangles
  resources :anagrams
  resources :palindromes
  resources :ordenators
  resources :calcs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"
end

app/models/palindrome.rb
class Palindrome < ApplicationRecord

  def is_palindrome(phrase_test)
    phrase_analisys = Palindrome.create(phrase: phrase_test)
    phrase_nospace = phrase_analisys.phrase.delete(" ").downcase
    phrase_nospace_reverse = phrase_nospace.reverse.downcase
    if phrase_nospace == phrase_nospace_reverse
      puts "É um palíndromo"
    elsif phrase_analisys.phrase == " " || phrase_analisys.phrase == "nulo"
      puts "Nulo ou em branco, não há como ser analisado"
    else
      puts "Não é um palíndromo"
    end
  end

end

app/controllers/palindromes_controller.rb
class PalindromesController < ApplicationController
  before_action :set_palindrome, only: [:show, :edit, :update, :destroy]

  # GET /palindromes
  # GET /palindromes.json
  def index
    @palindromes = Palindrome.all
  end

  # GET /palindromes/1
  # GET /palindromes/1.json
  def show
  end

  # GET /palindromes/new
  def new
    @palindrome = Palindrome.new
  end

  # GET /palindromes/1/edit
  def edit
  end

  # POST /palindromes
  # POST /palindromes.json
  def create
    @palindrome = Palindrome.new(palindrome_params)

    respond_to do |format|
      if @palindrome.save
        format.html { redirect_to @palindrome, notice: 'Palindrome was successfully created.' }
        format.json { render :show, status: :created, location: @palindrome }
      else
        format.html { render :new }
        format.json { render json: @palindrome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /palindromes/1
  # PATCH/PUT /palindromes/1.json
  def update
    respond_to do |format|
      if @palindrome.update(palindrome_params)
        format.html { redirect_to @palindrome, notice: 'Palindrome was successfully updated.' }
        format.json { render :show, status: :ok, location: @palindrome }
      else
        format.html { render :edit }
        format.json { render json: @palindrome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palindromes/1
  # DELETE /palindromes/1.json
  def destroy
    @palindrome.destroy
    respond_to do |format|
      format.html { redirect_to palindromes_url, notice: 'Palindrome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palindrome
      @palindrome = Palindrome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palindrome_params
      params.require(:palindrome).permit(:phrase, :is_palindrome)
    end
end

app/helpers/palindromes_helper.rb
module PalindromesHelper
end

app/views/palindromes/_form.html.erb
<%= form_with(model: palindrome, local: true) do |form| %>
  <% if palindrome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(palindrome.errors.count, "error") %> prohibited this palindrome from being saved:</h2>

      <ul>
      <% palindrome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :phrase %>
    <%= form.text_field :phrase %>
  </div>

  <div class="field">
    <%= form.label :is_palindrome %>
    <%= form.check_box :is_palindrome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/palindromes/edit.html.erb
<h1>Editing Palindrome</h1>

<%= render 'form', palindrome: @palindrome %>

<%= link_to 'Show', @palindrome %> |
<%= link_to 'Back', palindromes_path %>

app/views/palindromes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Palindromes</h1>

<table>
  <thead>
    <tr>
      <th>Phrase</th>
      <th>Is palindrome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @palindromes.each do |palindrome| %>
      <tr>
        <td><%= palindrome.phrase %></td>
        <td><%= palindrome.is_palindrome %></td>
        <td><%= link_to 'Show', palindrome %></td>
        <td><%= link_to 'Edit', edit_palindrome_path(palindrome) %></td>
        <td><%= link_to 'Destroy', palindrome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Palindrome', new_palindrome_path %>

app/views/palindromes/new.html.erb
<h1>New Palindrome</h1>

<%= render 'form', palindrome: @palindrome %>

<%= link_to 'Back', palindromes_path %>

app/views/palindromes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phrase:</strong>
  <%= @palindrome.phrase %>
</p>

<p>
  <strong>Is palindrome:</strong>
  <%= @palindrome.is_palindrome %>
</p>

<%= link_to 'Edit', edit_palindrome_path(@palindrome) %> |
<%= link_to 'Back', palindromes_path %>