config/routes.rb
Rails.application.routes.draw do
  resources :triangles
  resources :anagrams
  resources :palindromes
  resources :ordenators
  resources :calcs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"
end

app/models/anagram.rb
class Anagram < ApplicationRecord

  def is_anagram(word_test_one, word_test_two)
    word_analisys = Anagram.create(word_one: word_test_one, word_two: word_test_two)
    word_one_nospace = word_analisys.word_one.delete(" ").downcase.chars.sort.join unless !word_analisys.word_one # palavra 1
    word_two_nospace = word_analisys.word_two.delete(" ").downcase.chars.sort.join unless !word_analisys.word_two # palavra 2
    
    if !word_one_nospace.blank? && !word_two_nospace.blank? && word_one_nospace && word_two_nospace && word_one_nospace == word_two_nospace
      puts "É um anagrama"
    elsif word_analisys.word_one == " " && word_analisys.word_two == " "
      puts "Palavra em branco, não há como ser analisado"
    elsif !word_analisys.word_one && !word_analisys.word_two
      puts "Palavra nula, não há como ser analisado"
    else
      puts "Não é um anagrama"
    end
  end

end

app/controllers/anagrams_controller.rb
class AnagramsController < ApplicationController
  before_action :set_anagram, only: [:show, :edit, :update, :destroy]

  # GET /anagrams
  # GET /anagrams.json
  def index
    @anagrams = Anagram.all
  end

  # GET /anagrams/1
  # GET /anagrams/1.json
  def show
  end

  # GET /anagrams/new
  def new
    @anagram = Anagram.new
  end

  # GET /anagrams/1/edit
  def edit
  end

  # POST /anagrams
  # POST /anagrams.json
  def create
    @anagram = Anagram.new(anagram_params)

    respond_to do |format|
      if @anagram.save
        format.html { redirect_to @anagram, notice: 'Anagram was successfully created.' }
        format.json { render :show, status: :created, location: @anagram }
      else
        format.html { render :new }
        format.json { render json: @anagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anagrams/1
  # PATCH/PUT /anagrams/1.json
  def update
    respond_to do |format|
      if @anagram.update(anagram_params)
        format.html { redirect_to @anagram, notice: 'Anagram was successfully updated.' }
        format.json { render :show, status: :ok, location: @anagram }
      else
        format.html { render :edit }
        format.json { render json: @anagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anagrams/1
  # DELETE /anagrams/1.json
  def destroy
    @anagram.destroy
    respond_to do |format|
      format.html { redirect_to anagrams_url, notice: 'Anagram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anagram
      @anagram = Anagram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anagram_params
      params.require(:anagram).permit(:word_one, :word_two, :is_anagram)
    end
end

app/helpers/anagrams_helper.rb
module AnagramsHelper
end

app/views/anagrams/_form.html.erb
<%= form_with(model: anagram, local: true) do |form| %>
  <% if anagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anagram.errors.count, "error") %> prohibited this anagram from being saved:</h2>

      <ul>
      <% anagram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :word_one %>
    <%= form.text_field :word_one %>
  </div>

  <div class="field">
    <%= form.label :word_two %>
    <%= form.text_field :word_two %>
  </div>

  <div class="field">
    <%= form.label :is_anagram %>
    <%= form.check_box :is_anagram %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/anagrams/edit.html.erb
<h1>Editing Anagram</h1>

<%= render 'form', anagram: @anagram %>

<%= link_to 'Show', @anagram %> |
<%= link_to 'Back', anagrams_path %>

app/views/anagrams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anagrams</h1>

<table>
  <thead>
    <tr>
      <th>Word one</th>
      <th>Word two</th>
      <th>Is anagram</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anagrams.each do |anagram| %>
      <tr>
        <td><%= anagram.word_one %></td>
        <td><%= anagram.word_two %></td>
        <td><%= anagram.is_anagram %></td>
        <td><%= link_to 'Show', anagram %></td>
        <td><%= link_to 'Edit', edit_anagram_path(anagram) %></td>
        <td><%= link_to 'Destroy', anagram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anagram', new_anagram_path %>

app/views/anagrams/new.html.erb
<h1>New Anagram</h1>

<%= render 'form', anagram: @anagram %>

<%= link_to 'Back', anagrams_path %>

app/views/anagrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word one:</strong>
  <%= @anagram.word_one %>
</p>

<p>
  <strong>Word two:</strong>
  <%= @anagram.word_two %>
</p>

<p>
  <strong>Is anagram:</strong>
  <%= @anagram.is_anagram %>
</p>

<%= link_to 'Edit', edit_anagram_path(@anagram) %> |
<%= link_to 'Back', anagrams_path %>